//
// Created by jakub on 06.01.18.
//

#ifndef SERVER_SERVERCONFIG_H
#define SERVER_SERVERCONFIG_H

#define BUFFER_SIZE 1000
#define QUEUE_SIZE 5

#define DEFAULT_PORT 10001
#define DEFAULT_ADDR "127.0.0.1"

#define DEFAULT_INTERFACE "eth0"

#endif //SERVER_SERVERCONFIG_H
